name: Build Android (raw upload)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.5

      - name: Install Haxelibs
        run: |
          haxelib setup /home/runner/haxelib
          haxelib install hxcpp
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib run lime setup flixel
          haxelib install flixel-ui
          haxelib install flixel-tools
          haxelib install flixel-addons 2.11.0
          haxelib install hscript
          haxelib git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd.git
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit.git
          haxelib git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile Game
        run: haxelib run lime build android -release

      - name: Prepare Artifact
        run: |
          mkdir -p artifact
          cp export/release/android/bin/app/build/outputs/apk/debug/*.apk artifact/ || echo "APK not found"
          zip -r android_build.zip artifact/

      - name: Upload Zip (raw)
        uses: actions/upload-pages-artifact@v4
        with:
          path: .
