name: Build Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib --quiet setup /home/runner/haxelib
          haxelib --quiet install hxcpp > /dev/null
          haxelib --quiet install lime 7.9.0
          haxelib --quiet install openfl 9.1.0
          haxelib --quiet --never install flixel 4.11.0
          haxelib --quiet run lime setup flixel
          haxelib --quiet install flixel-tools
          haxelib --quiet install flixel-ui
          haxelib --quiet install hscript
          haxelib --quiet install flixel-addons 2.11.0
          haxelib --quiet git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd.git
          haxelib --quiet git linc_luajit https://github.com/Sirox228/linc_luajit.git
          haxelib --quiet git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools
          haxelib list

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build android -release

      - name: Create artifacts folder
        run: |
          mkdir -p artifacts
          cp export/release/android/bin/app/build/outputs/apk/debug/*.apk artifacts/ || echo "No APK found"

      # Upload usando ação alternativa confiável
      - name: Upload APK (backup method)
        uses: dawidd6/action-upload-artifact@v2
        with:
          name: androidBuild
          path: artifacts/
